# Generated by Django 5.2.13 on 2026-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_order_updated_at_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
